### PR TITLE
Build UppercuT with latest version of UppercuT

### PR DESCRIPTION
**Pull request by coxp**

### CODE REVIEW

**Comment by coxp** [comment]
Sorry for the large commit, the main change is just to use the .build directory from the build output to replace the existing build directory.

The only remaining issue I can see is the change to specify the product version. If you look at the generated uc.exe the Product Version on the details tab is set to "versioning.for.uc-1-ga8639d4". This seems to be due to the following line change from

https://github.com/chucknorris/uppercut/blob/master/build/versionBuilder.step#L96

to

https://github.com/chucknorris/uppercut/blob/master/product/uppercut.build/.build/versionBuilder.step#L54

I'm not sure what properties to set to mimic the old behaviour.

**Comment by coxp** [comment]
Also sorry for the multiple commits in a single pull request! I'd started down a path and hadn't realised that all my commits would go in the same request.

**Comment by ferventcoder** [comment]
@coxp you may want to explore using feature branches, so you can separate your commits.

**Comment by ferventcoder** [comment]
I'd actually prefer that each of the bits are split into separate branches so that each can be evaluated separately.

**Comment by coxp** [comment]
Sorry Rob, I'm not sure how to rebase commits into separate feature branches especially when they're dependent on the 1st commit.

**Comment by ferventcoder** [comment]
@coxp That's the easy part. `git rebase --onto`

But I'd suggest getting Git Extensions installed so you can better visualize the commits as you go through this process. In short, it's about impossible for us to review and pull in changes against a master branch.

**Comment by ferventcoder** [comment]
Also `git rebase -i` allows you to reorder commits and a bunch of other powerful things. I just used it yesterday to move a set of commits further back in history against an older commit on the master branch so I could do something that required the code not to be using what was just merged in recently. 

Git is super powerful. It boggles the mind sometimes.

**Comment by ferventcoder** [comment]
Ruh roh - what closed this? Removal of the original repository? Apologies, git doesn't notify when updated commits are pushed and this fell off of my radar.

**Pull request closed without merging**
